apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vaultline-backend
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - vaultline
  selector:
    matchLabels:
      app: vaultline-backend
  endpoints:
    - targetPort: 3001
      path: /metrics
      interval: 15s