apiVersion: v1
kind: Service
metadata:
  name: vaultline-backend
  namespace: vaultline
  labels:
    app: vaultline-backend
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: vaultline-backend